// GwPopup
import GwPopupLayout from './GwPopupLayout'; 
import GwPopupController from './GwPopupController'; 
import dom_util from './dom_util';
import components from './components'; 

// For Init 
function popupInit(Vue, option){
	// Register Component Global; 
	components.register(Vue); 

	// Blur Effect On $app Generated By `option.getApp`; 
	GwPopupController.__setPrototype('onBlur', function(){
		let $app = option.getApp(); 

		$app.setAttribute('class', 'isBlur'); 
	})

	GwPopupController.__setPrototype('offBlur', function(){
		let $app = option.getApp(); 

		$app.setAttribute('class', ''); 
	})
}

// export default
let GwPopup = {}; 
// Counter; 
let COUNT = 0; 

GwPopup.install = function(Vue, option){
	// Init 
	popupInit(Vue, option); 

	// Create; 
	let $popup = dom_util.createRoot(); 

	// Set Selector; 
	GwPopupLayout.el = $popup; 

	// All Done  
	GwPopupLayout.created = function(){
		console.log('[ GwPopupLayout onReady ]'); 
	}

	// Add On For Calling Sub-component   
	GwPopupLayout.methods.push = function(option){
		let item = GwPopupController.create(option); 

		this.list.push(item); 

		return item; 
	}

	GwPopupLayout.methods.pop = function(){
		return this.list.pop();
	}

	// Instancing popup; 
	let popup_vm = new Vue(GwPopupLayout); 

	// mount to prototype for all vue instances  
	Vue.prototype.$popup = popup_vm; 
}

export default GwPopup; 
